# Generated by Django 4.1.7 on 2023-03-04 20:56

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("moves", "0001_initial_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True,
                        upload_to=apps.accounts.models._get_new_name,
                        validators=[
                            apps.accounts.models._validate_file_extension
                        ],
                    ),
                ),
                ("moves", models.ManyToManyField(to="moves.move")),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
